module.exports = {
  topics: [
    {
      id: 1,
      title: 'Found the cliff this Clif bar came from',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 2,
      title: 'TIL that in 2015, a Louisiana man was arrested for drunkenly riding a horse on a highway. When detained, he said, "The horse knows the way home" and the sheriff concluded it did not constitute DUI.',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 3,
      title: 'Wait for it',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 4,
      title: 'me irl',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 5,
      title: 'Correlation vs. Causation: Number of IKEA Stores vs. Number of Nobel Laureates per country [OC]',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 6,
      title: 'Perfect can crush',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 7,
      title: 'Long exposure shot of me spinning fire',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 8,
      title: 'McNugget Mystery',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 9,
      title: 'Hundreds of Missouri\'s 15-year-old brides may have married their rapists',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 10,
      title: 'Bitwise',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 11,
      title: 'Learn about computers by building one',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 12,
      title: 'How your ethereum can be stolen through DNS rebinding',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 13,
      title: 'Writing Simple Haskell',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 14,
      title: 'Snips open sources its Natural Language Understanding Python library',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 15,
      title: 'gitleaks: Verify a git repo for stored secrets and keys',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 16,
      title: 'It\'s perfectly fine to only code at work, don\'t let anyone tell you otherwise',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 17,
      title: 'Why I Quit Google to Work for Myself',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 18,
      title: 'Self-taught, free CS education',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 19,
      title: 'Why every user agent string start with "Mozilla"',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 20,
      title: 'JavaFX will be removed from the Java JDK',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 21,
      title: 'JavaFX will be removed from the Java JDK',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
    {
      id: 22,
      title: 'JavaFX will be removed from the Java JDK',
      upvotes: Math.floor(Math.random() * 10000),
      comments: ['dumb', 'cool!,', 'That does not make sense!'],
    },
  ],
};
